/* eslint-disable import/prefer-default-export */
import betterSqlLite from 'better-sqlite3';

import { JWT } from 'google-auth-library';
import { getAllEntities } from './sheets';
import DatabaseInterface from './databaseInterface';
import { ConfigInterface } from './types';

export const createDatabase = async (config: ConfigInterface): Promise<betterSqlLite.Database> => {
  const {
    apiKey, docId, sheetId, mapFunction, primaryKey, serviceAccountEmail, serviceAccountKey,
  } = config;

  if (!mapFunction) {
    throw new Error('mapFunction is a required config parameter.');
  }

  if (!apiKey && !serviceAccountEmail) {
    throw new Error('One of apiKey or serviceAccountEmail must be provided as a config parameter.');
  }

  if (!docId) {
    throw new Error('docId is a required config parameter.');
  }

  if (!sheetId) {
    throw new Error('sheetId is a required config parameter.');
  }

  const authMethod = apiKey || new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: serviceAccountEmail,
    key: serviceAccountKey,
    scopes: [
      'https://www.googleapis.com/auth/spreadsheets',
    ],
  });

  const data = await getAllEntities(authMethod, docId, sheetId, mapFunction, primaryKey);
  const databaseInterface = new DatabaseInterface(config);
  await databaseInterface.createTable(data);
  await databaseInterface.seed(data);
  await databaseInterface.createNormalizedTable({ data, ...config });
  await databaseInterface.createColumnBreakoutTables({ data, ...config });
  return databaseInterface.db;
};
